// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsjv7PPNJ2JaoECKnfakccCRxoyzjleyo',
    appId: '1:516476001122:web:49cccd90c51876406bea3b',
    messagingSenderId: '516476001122',
    projectId: 'quick-ride-7df1e',
    authDomain: 'quick-ride-7df1e.firebaseapp.com',
    storageBucket: 'quick-ride-7df1e.appspot.com',
    measurementId: 'G-SEVG6RFPKR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUdj_mPxeN9e1t7eSLMNtk1CrOMDbdsZc',
    appId: '1:516476001122:ios:c2bff66c0538d0436bea3b',
    messagingSenderId: '516476001122',
    projectId: 'quick-ride-7df1e',
    storageBucket: 'quick-ride-7df1e.appspot.com',
    iosBundleId: 'com.robbochinni.tamDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUdj_mPxeN9e1t7eSLMNtk1CrOMDbdsZc',
    appId: '1:516476001122:ios:c2bff66c0538d0436bea3b',
    messagingSenderId: '516476001122',
    projectId: 'quick-ride-7df1e',
    storageBucket: 'quick-ride-7df1e.appspot.com',
    iosBundleId: 'com.robbochinni.tamDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsjv7PPNJ2JaoECKnfakccCRxoyzjleyo',
    appId: '1:516476001122:web:8c51fb35dc2abaf36bea3b',
    messagingSenderId: '516476001122',
    projectId: 'quick-ride-7df1e',
    authDomain: 'quick-ride-7df1e.firebaseapp.com',
    storageBucket: 'quick-ride-7df1e.appspot.com',
    measurementId: 'G-SQ2JGDFSTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSUHEn3HrCluBkYH0Wq0EGIsgmu46KV8',
    appId: '1:516476001122:android:bcb2a9be68d2f3786bea3b',
    messagingSenderId: '516476001122',
    projectId: 'quick-ride-7df1e',
    storageBucket: 'quick-ride-7df1e.appspot.com',
  );

}